contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hymenopteraanalysis channel"
    url: https://nfcore.slack.com/channels/hymenopteraanalysis
    about: Discussion about the nf-core/hymenopteraanalysis pipeline
